name: Deploy Shopify Theme

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
      SHOPIFY_FLAG_STORE: milano-bags-peru.myshopify.com
      THEME_ID: 146105172133

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Push & publish theme 🚀
        run: shopify theme push --theme=$THEME_ID --publish --allow-live
